# Generated by Django 2.0.2 on 2018-02-23 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('f_fundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('f_fundacion', models.DateField()),
                ('animador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Animador')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('reglas', models.IntegerField()),
                ('graficos', models.IntegerField()),
                ('controles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=100)),
                ('f_lanzamiento', models.DateField()),
                ('version', models.CharField(max_length=100)),
                ('descargas', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=3)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Desarrollador')),
                ('valoraciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Valoraciones')),
            ],
        ),
        migrations.AddField(
            model_name='plataforma',
            name='videojuego',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacion.Videojuego'),
        ),
    ]
