# Generated by Django 2.0.2 on 2018-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='videojuego',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataforma',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacion.Plataforma'),
        ),
    ]
