# Generated by Django 2.0.3 on 2018-04-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='media',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='procesador',
        ),
    ]
